server:
  port: 8082
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
info:
  project:
    version: 1.0-SNAPSHOT
    title: ms-exchange
    description: Exchange System
    expose.package: com.everis.exchange.controller
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
