DROP TABLE IF EXISTS EXCHANGE;
CREATE TABLE EXCHANGE (
    ID NUMERIC(19,0) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    BUY NUMERIC(19,2) NOT NULL,
    SELL NUMERIC(19,2) NOT NULL,
    DATE TIMESTAMP
);

